name: Deploy Backend

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Trigger Render Deploy
        run: |
          curl -X POST -d '{}' ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
