# version: "3.8"

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    build:
      context: ./client
    ports:
      - "80:80"

  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
