name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main # Change to match the branch you use

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build Docker Image for Frontend (from client folder)
      - name: Build Frontend Docker Image
        run: |
          cd client  # Move to frontend folder (client)
          docker build -t docker.io/rashid29/frontend:latest .

      # Step 3: Push Docker Image to Docker Hub
      - name: Push Frontend Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push docker.io/rashid29/frontend:latest

      # Step 4: Trigger Deployment on Render (Frontend)
      - name: Deploy Frontend to Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}"
