name: Deploy Frontend

on:
  push:
    paths:
      - "client/**"
      - ".github/workflows/frontend-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nari-frontend:latest ./client

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nari-frontend:latest

      - name: Trigger Render Deploy
        run: curl -X POST -d '{}' ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
