name: Deploy Frontend

on:
  push:
    paths:
      - "client/**" # Trigger on changes in the client folder

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up versioning
        id: versioning
        run: |
          TAG=${{ github.ref_name }}  # Use the branch name or tag name
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=${{ github.ref_name }}  # Extract tag name if it's a tag push
          elif [[ "${{ github.ref }}" == refs/heads/* ]]; then
            TAG=${{ github.sha::7 }}  # Use short commit hash for branches
          else
            TAG="latest"  # Fallback to latest if no tag or branch
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nari-frontend:${{ env.IMAGE_TAG }} ./client

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nari-frontend:${{ env.IMAGE_TAG }}

      - name: Trigger Render Deploy
        run: curl -X POST -d '{}' ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
